### ISSUE TITLE
Fix pip installation command in README

### ISSUE THREAD

**Issue by EteimZ** [J0/django-storage-supabase#1]
Hi @J0 awesome work you have done here with the package. I noticed a typo in the README. Currently can't install the package from the command in the README.

It says:
```bash
pip3 install django-storages-supabase
``` 

but this doesn't work but on pypi it says:

```bash
pip install django-storage-supabase
```

This works and I was able to successfully install the package.

**Comment by J0** [comment]
Hey @EteimZ,

Thanks for the catch! 

 I'll fix it in a second
